language: php
php:
  - 5.3.3
  - 5.4
branches:
  only:
  - /^7.x/
env:
  - FEDORA_VERSION="3.5"
  - FEDORA_VERSION="3.6.2"
  - FEDORA_VERSION="3.7.0"
before_install:
  - cd $HOME
  - git clone -b 7.x git://github.com/Islandora/islandora.git
  - git clone -b 7.x git://github.com/Islandora/islandora_solution_pack_collection.git
  - git clone -b 7.x git://github.com/discoverygarden/islandora_jodconverter.git
  - export ISLANDORA_DIR=$HOME/islandora
  - $HOME/islandora/tests/scripts/travis_setup.sh
  - $TRAVIS_BUILD_DIR/tests/scripts/travis_setup.sh
  - cd $HOME/drupal-*
  - ln -s $TRAVIS_BUILD_DIR sites/all/modules/islandora_solution_pack_document
  - ln -s $HOME/islandora_solution_pack_collection sites/all/modules/islandora_solution_pack_collection
  - ln -s $HOME/islandora_jodconverter sites/all/modules/islandora_jodconverter
  - drush dl imagemagick
  - drush dl libraries
  - drush en --user=1 --yes imagemagick islandora_basic_collection islandora_document
script:
  - ant -buildfile sites/all/modules/islandora_solution_pack_document/build.xml lint
  - $ISLANDORA_DIR/tests/scripts/line_endings.sh sites/all/modules/islandora_solution_pack_document
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora_document
  - phpcpd --names *.module,*.inc,*.test sites/all/modules/islandora_solution_pack_document
  - drush test-run --uri=http://localhost:8081 "Islandora Document"
  - drush wd-show --count=500
